[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.5"
rand_chacha="0.3.0"
sha2="0.10.6"
hex="0.4.3"
pbkdf2 = "0.11.0"
hmac="0.12.1"
secp256k1="0.25.0"
num="0.4.0"